project:
  type: website

website:
  navbar: 
    left:
      - text: "<img src='images/icms2025.png' alt='iCMS 2025 Logo' style='height:50px; vertical-align:middle;'><span style='color: black;'>iCMS 2025</span>"
        file: index.qmd

    right:
      - text: "<span style='color: black;'>About iCMS 2025</span>"
        file: about.qmd
      - text: "<span style='color: black;'>Call for paper</span>"
        menu:
          - text: "<span style='color: black;'>Important Dates</span>"
            file: call_for_papers.qmd
          - text: "Tracks"
            file: tracks.qmd
          - text: "<span style='color: black;'>Publications Opportunity</span>"
            file: publications.qmd
      - text: "<span style='color: black;'>Registration & Submission</span>"
        file: register.qmd
      - text: "<span style='color: black;'>Fees & Payment</span>"
        file: fees.qmd
      - text: "<span style='color: black;'>Our Teams</span>"
        file: our_teams.qmd
      - text: "<span style='color: black;'>Contact</span>"
        file: contacts.qmd
  sidebar:
    style: "floating"
    search: false
    pinned: false 
    contents:
      - section: "<span style='color: black;'>**Walk through the websites**</span>"
        contents:
          - text: "<img src='images/icms2025.png' alt='iCMS 2025 Logo' style='height:20px;'><span style='color: black;'>iCMS 2025</span>"
            href: index.qmd
          - text: "<span style='color: black;'>iCMS 2021</span>"
            href: https://uitmicms.wixsite.com/icms2021
            target: _blank
          - text: "<span style='color: black;'>iCMS 2019</span>"
            href: https://uitmicms.wixsite.com/icms2019
            target: _blank
          # - text: "Call for Papers"
          #   href: callforpapers.qmd
          # - text: "🔵 See the code in R"
          #   href: r.qmd
          # - icon: github
          #   text: "See the code on GitHub"
          #   href: https://github.com/posit-marketing/taylor-swift-tour
          #   target: _blank
          # - text: "☁️ Open the project in Posit Cloud"
          #   href: https://posit.cloud/content/7059961
          #   target: _blank
    footer: icms2021_playlist.html
  page-footer:
    center: |
       <a href="https://posit.co"><img src="images/posit-logo.png" alt="Posit logo" style="width:60px;"></a> 
    # left:
    #   - href: references.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/posit-software/
        aria-label: Posit LinkedIn
      - icon: mastodon
        href: https://fosstodon.org/@Posit
        aria-label: Posit Mastodon
      - icon: tiktok
        href: https://www.tiktok.com/@posit_pbc
        aria-label: Posit TikTok
      - icon: instagram
        href: https://www.instagram.com/posit.pbc/
        aria-label: Posit Instagram
        
execute:
  freeze: true

format:
  html:
    theme: cosmo
    mainfont: Lato
    css: style.css
    execute:
      echo: true
      eval: false
      fig-align: center
      message: false
      warning: false
    grid:
      sidebar-width: 300px
    include-in-header: 
      - progress-bar.html
    lightbox: auto
    page-layout: article
  